name: Vampirism

on:
  push:
    branches:
      - main

jobs:
  copy_repositories:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List repositories and branches
      run: |
        echo "Repository: REPO1, Branch: main" >> repositories.txt
        echo "Repository: REPO2, Branch: dev" >> repositories.txt
        # Добавьте другие репозитории и ветки по необходимости
        
    - name: Create files with repository and branch info
      run: |
        ls
        mkdir files
        cp repositories.txt files/
        
    - name: Clone target repository
      uses: actions/checkout@v2
      with:
        repository: your_username/your_target_repository
        token: ${{ secrets.VAMP }}
        
    - name: Copy files to target repository
      run: |
        cp -r files/* your_target_repository/
        
    - name: Commit and push changes
      run: |
        cd your_target_repository
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Add repository and branch info"
        git push
